---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: abc-tech-deployment
spec:
  replicas: 3
  selector:
    matchLables:
      app: abc-tech
  template:
    metadata:
      labels:
        app: abc-tech
    spec:
      containers:
        - name: abc-app
          image: akulshah/abc-tech:latest
          port:
            - containerPort: 6000
