---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: abc-tech-deployment
  labels:
    app: abc-tech
spec:
  replicas: 3
  selector:
    matchLabels:
      app: abc-tech
  template:
    metadata:
      labels:
        app: abc-tech
    spec:
      containers:
      - name: abc-tech
        image: akulshah/abc-tech:
        ports:
        - containerPort: 6000
