apiVersion : apps/v1
kind: Deployment
metadata:
  name: abc-tech-deploy
spec:
  selector:
    matchLables:
      app: abc-deploy
  replicas: 3
  template:
    metadata:
      labels:
        app:abc-deploy
    spec:
      containers:
      - name: abc-app
        image: akulshah/abc-tech:latest
        port:
        - containerPort:8080
