---
apiVersion: v1
kind: Service
metadata:
  name: abc-nodeport-svc
spec:
  selector:
    app.kubernetes.io/name: abc-tech
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: NodePort
